# Generated by Django 3.0.1 on 2019-12-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name_plural': 'historicos audiologicos'},
        ),
        migrations.AlterField(
            model_name='historico',
            name='dis_c_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dis. c/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dis_od',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dis OD %'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dis_od_db',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dis OD dB'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dis_oe',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dis OE %'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dis_oe_db',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dis OE dB'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dis_s_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dis. s/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dt_iprf',
            field=models.DateField(verbose_name='Data Av. Audiologica'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dt_tpf',
            field=models.DateField(verbose_name='Data AV. Campo Livre'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='hhia_od_c_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HHIA OD c/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='hhia_od_s_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HHIA OD s/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='hhia_oe_c_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HHIA OE c/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='hhia_oe_s_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HHIA OE s/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='lrf_od',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='LRF OD dB'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='lrf_oe',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='LRF OE dB'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='mono_c_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mono c/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='mono_od',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mono OD %'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='mono_od_db',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mono OD dB'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='mono_oe',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mono OE %'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='mono_oe_db',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mono OE dB'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='mono_s_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=' Mono s/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='sss_c_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SSS c/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='sss_s_aasi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SSS s/ AASI'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='tempo_uso',
            field=models.DateField(verbose_name='Quanto tempo'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='uso_aparelho',
            field=models.CharField(blank=True, choices=[('sim', 'SIM'), ('nao', 'NAO')], max_length=3, null=True, verbose_name='Ja usou AASI?'),
        ),
    ]
