# Generated by Django 3.0.1 on 2019-12-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_auto_20191230_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='img_iprf',
            field=models.ImageField(blank=True, null=True, upload_to='website/img/% Y/% m/% d/', verbose_name='Nivel de audicao IPRF'),
        ),
        migrations.AddField(
            model_name='historico',
            name='img_tpf',
            field=models.ImageField(blank=True, null=True, upload_to='website/img/% Y/% m/% d/', verbose_name='Nivel de audicao TPF'),
        ),
    ]
