# Generated by Django 3.0.1 on 2019-12-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dt_alteacao',
            field=models.DateField(auto_now=True, null=True, verbose_name='modificado em'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dt_criacao',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profissional',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='profissional.Profissional'),
        ),
    ]
