# Generated by Django 3.0.1 on 2019-12-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20191218_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='data_nascimento',
            new_name='dt_nascimento',
        ),
    ]
