# Generated by Django 3.0.1 on 2019-12-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20191218_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data nascimento'),
        ),
    ]
