# Generated by Django 3.0.1 on 2019-12-18 11:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('tempo_de_servico', models.IntegerField(blank=True, default=0, null=True)),
                ('especialidade', models.CharField(choices=[('f', 'Fonoaudiologo'), ('p', 'Psicologo'), ('n', 'Neurologista')], default='f', max_length=1, verbose_name='especialidade')),
            ],
            options={
                'verbose_name_plural': 'profissionais',
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
