# Generated by Django 3.0.1 on 2019-12-18 18:51

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0004_auto_20191218_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa', models.CharField(blank=True, max_length=100, null=True)),
                ('tempo_deficiencia', models.IntegerField(blank=True, null=True)),
                ('causa', models.CharField(blank=True, max_length=100, null=True)),
                ('historico_familiar', models.TextField(blank=True, null=True)),
                ('dificuldade', multiselectfield.db.fields.MultiSelectField(choices=[('v', 'TV'), ('f', 'Telefone'), ('e', 'Encontros e Reuniões'), ('r', 'Ambientes Ruidosos'), ('i', 'Igrejas'), ('t', 'Trabalho')], max_length=1)),
                ('zumbido', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_zumbido', models.CharField(blank=True, max_length=60, null=True)),
                ('infeccao', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_infeccao', models.CharField(blank=True, max_length=60, null=True)),
                ('cirurgia_ouvido', models.CharField(blank=True, max_length=60, null=True)),
                ('destreza_manual', models.CharField(blank=True, max_length=60, null=True)),
                ('problema_visual', models.CharField(blank=True, max_length=60, null=True)),
                ('protese_dentaria', models.CharField(blank=True, max_length=60, null=True)),
                ('medicamento', models.CharField(blank=True, max_length=60, null=True)),
                ('hipertensao', models.CharField(blank=True, max_length=60, null=True)),
                ('paciente', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
