# Generated by Django 3.0.1 on 2019-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='dificuldade',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dif_ar',
            field=models.CharField(choices=[('s', 'SIM'), ('n', 'NAO')], default='n', max_length=1, verbose_name='Ambientes Ruidosos'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dif_er',
            field=models.CharField(choices=[('s', 'SIM'), ('n', 'NAO')], default='n', max_length=1, verbose_name='Encontros e Reuniões'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dif_fone',
            field=models.CharField(choices=[('s', 'SIM'), ('n', 'NAO')], default='n', max_length=1, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dif_igreja',
            field=models.CharField(choices=[('s', 'SIM'), ('n', 'NAO')], default='n', max_length=1, verbose_name='Igrejas'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dif_trabalho',
            field=models.CharField(choices=[('s', 'SIM'), ('n', 'NAO')], default='n', max_length=1, verbose_name='Trabalho'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dif_tv',
            field=models.CharField(choices=[('s', 'SIM'), ('n', 'NAO')], default='n', max_length=1, verbose_name='TV'),
        ),
    ]
