# Generated by Django 3.0.1 on 2019-12-30 17:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('fone', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('f', 'Fonoaudiologo'), ('p', 'Psicologo'), ('n', 'Neurologista')], default='f', max_length=1, verbose_name='especialidade')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
